<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="3" failed="1" ignored="0" total="12" passed="8">
  <reporter-output>
  </reporter-output>
  <suite name="Test" duration-ms="25336" started-at="2018-02-16T15:27:27Z" finished-at="2018-02-16T15:27:52Z">
    <groups>
      <group name="fail">
        <method signature="FallTest.nonExistFunctionFailTest()[pri:0, instance:simpleTests.FallTest@16a7124]" name="nonExistFunctionFailTest" class="simpleTests.FallTest"/>
      </group> <!-- fail -->
      <group name="smoke">
        <method signature="PetTests.simplePet()[pri:0, instance:simpleTests.PetTests@1192705]" name="simplePet" class="simpleTests.PetTests"/>
        <method signature="StoreTest.createOrder()[pri:0, instance:simpleTests.StoreTest@6642a5]" name="createOrder" class="simpleTests.StoreTest"/>
        <method signature="UserTests.simpleUser()[pri:0, instance:simpleTests.UserTests@c126dc]" name="simpleUser" class="simpleTests.UserTests"/>
      </group> <!-- smoke -->
    </groups>
    <test name="All tests" duration-ms="25336" started-at="2018-02-16T15:27:27Z" finished-at="2018-02-16T15:27:52Z">
      <class name="simpleTests.PetTests">
        <test-method status="PASS" signature="setData()[pri:0, instance:simpleTests.PetTests@1192705]" name="setData" is-config="true" duration-ms="10831" started-at="2018-02-16T15:27:27Z" finished-at="2018-02-16T15:27:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="simplePet()[pri:0, instance:simpleTests.PetTests@1192705]" name="simplePet" duration-ms="2921" started-at="2018-02-16T15:27:38Z" description="Create pet and delete it" finished-at="2018-02-16T15:27:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- simplePet -->
      </class> <!-- simpleTests.PetTests -->
      <class name="simpleTests.StoreTest">
        <test-method status="PASS" signature="checkInventory()[pri:0, instance:simpleTests.StoreTest@6642a5]" name="checkInventory" duration-ms="12588" started-at="2018-02-16T15:27:27Z" description="Get store inventory" finished-at="2018-02-16T15:27:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkInventory -->
        <test-method status="PASS" signature="createOrder()[pri:0, instance:simpleTests.StoreTest@6642a5]" name="createOrder" duration-ms="1633" started-at="2018-02-16T15:27:40Z" description="Create order and delete it" finished-at="2018-02-16T15:27:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createOrder -->
      </class> <!-- simpleTests.StoreTest -->
      <class name="simpleTests.UsersTest">
        <test-method status="PASS" signature="createUsers()[pri:0, instance:simpleTests.UsersTest@809b79]" name="createUsers" is-config="true" duration-ms="16" started-at="2018-02-16T15:27:41Z" finished-at="2018-02-16T15:27:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUsers -->
        <test-method status="PASS" signature="createNewUsersWithArray()[pri:0, instance:simpleTests.UsersTest@809b79]" name="createNewUsersWithArray" duration-ms="5171" started-at="2018-02-16T15:27:41Z" description="Create and delete users from array" finished-at="2018-02-16T15:27:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUsersWithArray -->
        <test-method status="PASS" signature="createUsers()[pri:0, instance:simpleTests.UsersTest@809b79]" name="createUsers" is-config="true" duration-ms="0" started-at="2018-02-16T15:27:41Z" finished-at="2018-02-16T15:27:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createUsers -->
        <test-method status="PASS" signature="createNewUsersWithList()[pri:0, instance:simpleTests.UsersTest@809b79]" name="createNewUsersWithList" duration-ms="5101" started-at="2018-02-16T15:27:41Z" description="Create and delete users from list" finished-at="2018-02-16T15:27:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUsersWithList -->
      </class> <!-- simpleTests.UsersTest -->
      <class name="simpleTests.UserTests">
        <test-method status="PASS" signature="login()[pri:0, instance:simpleTests.UserTests@c126dc]" name="login" duration-ms="2615" started-at="2018-02-16T15:27:41Z" description="Login and logout to created user" finished-at="2018-02-16T15:27:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- login -->
        <test-method status="PASS" signature="createNewUser()[pri:0, instance:simpleTests.UserTests@c126dc]" name="createNewUser" is-config="true" duration-ms="0" started-at="2018-02-16T15:27:41Z" finished-at="2018-02-16T15:27:41Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUser -->
        <test-method status="PASS" signature="createNewUser()[pri:0, instance:simpleTests.UserTests@c126dc]" name="createNewUser" is-config="true" duration-ms="0" started-at="2018-02-16T15:27:44Z" finished-at="2018-02-16T15:27:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUser -->
        <test-method status="PASS" signature="simpleUser()[pri:0, instance:simpleTests.UserTests@c126dc]" name="simpleUser" duration-ms="1886" started-at="2018-02-16T15:27:44Z" description="Create user and delete him" finished-at="2018-02-16T15:27:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- simpleUser -->
        <test-method status="PASS" signature="updateUser()[pri:0, instance:simpleTests.UserTests@c126dc]" name="updateUser" duration-ms="6497" started-at="2018-02-16T15:27:46Z" description="Update user name and phone" finished-at="2018-02-16T15:27:52Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateUser -->
        <test-method status="PASS" signature="createNewUser()[pri:0, instance:simpleTests.UserTests@c126dc]" name="createNewUser" is-config="true" duration-ms="0" started-at="2018-02-16T15:27:46Z" finished-at="2018-02-16T15:27:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- createNewUser -->
      </class> <!-- simpleTests.UserTests -->
      <class name="simpleTests.FallTest">
        <test-method status="PASS" signature="setData()[pri:0, instance:simpleTests.FallTest@16a7124]" name="setData" is-config="true" duration-ms="10831" started-at="2018-02-16T15:27:27Z" finished-at="2018-02-16T15:27:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="SKIP" signature="nonExistFunctionFailTest()[pri:0, instance:simpleTests.FallTest@16a7124]" name="nonExistFunctionFailTest" duration-ms="1403" started-at="2018-02-16T15:27:38Z" description="Call non-exist function" finished-at="2018-02-16T15:27:39Z">
          <exception class="exeptions.BaseException">
            <message>
              <![CDATA[get non-existent function]]>
            </message>
            <full-stacktrace>
              <![CDATA[exeptions.BaseException: get non-existent function
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:34)
at business.TestBO$AjcClosure1.run(TestBO.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at business.TestBO.callNonExistentFunction(TestBO.java:27)
at simpleTests.FallTest.nonExistFunctionFailTest(FallTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallConstructor(CallSiteArray.java:60)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:235)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$5.call(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:125)
at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:164)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at com.jayway.restassured.specification.ResponseSpecification$statusCode$1.callCurrent(Unknown Source)
at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCallCurrent(CallSiteArray.java:52)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:154)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at assertions.AssertStatusCode.assertStatusCodeIsOk(AssertStatusCode.java:11)
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:29)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- exeptions.BaseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nonExistFunctionFailTest -->
        <test-method status="SKIP" signature="nonExistFunctionFailTest()[pri:0, instance:simpleTests.FallTest@16a7124]" name="nonExistFunctionFailTest" duration-ms="316" started-at="2018-02-16T15:27:40Z" description="Call non-exist function" finished-at="2018-02-16T15:27:40Z">
          <exception class="exeptions.BaseException">
            <message>
              <![CDATA[get non-existent function]]>
            </message>
            <full-stacktrace>
              <![CDATA[exeptions.BaseException: get non-existent function
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:34)
at business.TestBO$AjcClosure1.run(TestBO.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at business.TestBO.callNonExistentFunction(TestBO.java:27)
at simpleTests.FallTest.nonExistFunctionFailTest(FallTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$5.call(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at com.jayway.restassured.specification.ResponseSpecification$statusCode$1.callCurrent(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at assertions.AssertStatusCode.assertStatusCodeIsOk(AssertStatusCode.java:11)
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:29)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- exeptions.BaseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nonExistFunctionFailTest -->
        <test-method status="PASS" signature="setData()[pri:0, instance:simpleTests.FallTest@16a7124]" name="setData" is-config="true" duration-ms="0" started-at="2018-02-16T15:27:40Z" finished-at="2018-02-16T15:27:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="SKIP" signature="nonExistFunctionFailTest()[pri:0, instance:simpleTests.FallTest@16a7124]" name="nonExistFunctionFailTest" duration-ms="316" started-at="2018-02-16T15:27:40Z" description="Call non-exist function" finished-at="2018-02-16T15:27:40Z">
          <exception class="exeptions.BaseException">
            <message>
              <![CDATA[get non-existent function]]>
            </message>
            <full-stacktrace>
              <![CDATA[exeptions.BaseException: get non-existent function
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:34)
at business.TestBO$AjcClosure1.run(TestBO.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at business.TestBO.callNonExistentFunction(TestBO.java:27)
at simpleTests.FallTest.nonExistFunctionFailTest(FallTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$5.call(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at com.jayway.restassured.specification.ResponseSpecification$statusCode$1.callCurrent(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at assertions.AssertStatusCode.assertStatusCodeIsOk(AssertStatusCode.java:11)
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:29)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- exeptions.BaseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nonExistFunctionFailTest -->
        <test-method status="PASS" signature="setData()[pri:0, instance:simpleTests.FallTest@16a7124]" name="setData" is-config="true" duration-ms="0" started-at="2018-02-16T15:27:40Z" finished-at="2018-02-16T15:27:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="PASS" signature="setData()[pri:0, instance:simpleTests.FallTest@16a7124]" name="setData" is-config="true" duration-ms="0" started-at="2018-02-16T15:27:40Z" finished-at="2018-02-16T15:27:40Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setData -->
        <test-method status="FAIL" signature="nonExistFunctionFailTest()[pri:0, instance:simpleTests.FallTest@16a7124]" name="nonExistFunctionFailTest" duration-ms="306" started-at="2018-02-16T15:27:40Z" description="Call non-exist function" finished-at="2018-02-16T15:27:41Z">
          <exception class="exeptions.BaseException">
            <message>
              <![CDATA[get non-existent function]]>
            </message>
            <full-stacktrace>
              <![CDATA[exeptions.BaseException: get non-existent function
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:34)
at business.TestBO$AjcClosure1.run(TestBO.java:1)
at org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
at io.qameta.allure.aspects.StepsAspects.step(StepsAspects.java:46)
at business.TestBO.callNonExistentFunction(TestBO.java:27)
at simpleTests.FallTest.nonExistFunctionFailTest(FallTest.java:25)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.retryFailed(Invoker.java:838)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1009)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
at java.lang.Thread.run(Thread.java:748)
Caused by: java.lang.AssertionError: 1 expectation failed.
Expected status code <200> doesn't match actual status code <404>.

at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
at org.codehaus.groovy.reflection.CachedConstructor.invoke(CachedConstructor.java:80)
at org.codehaus.groovy.reflection.CachedConstructor.doConstructorInvoke(CachedConstructor.java:74)
at org.codehaus.groovy.runtime.callsite.ConstructorSite$ConstructorSiteNoUnwrap.callConstructor(ConstructorSite.java:84)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callConstructor(AbstractCallSite.java:247)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure.validate(ResponseSpecificationImpl.groovy:598)
at com.jayway.restassured.internal.ResponseSpecificationImpl$HamcrestAssertionClosure$validate$5.call(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.validateResponseIfRequired(ResponseSpecificationImpl.groovy:760)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite$PogoCachedMethodSiteNoUnwrapNoCoerce.invoke(PogoMetaMethodSite.java:210)
at org.codehaus.groovy.runtime.callsite.PogoMetaMethodSite.callCurrent(PogoMetaMethodSite.java:59)
at org.codehaus.groovy.runtime.callsite.AbstractCallSite.callCurrent(AbstractCallSite.java:166)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:120)
at com.jayway.restassured.specification.ResponseSpecification$statusCode$1.callCurrent(Unknown Source)
at com.jayway.restassured.internal.ResponseSpecificationImpl.statusCode(ResponseSpecificationImpl.groovy:128)
at com.jayway.restassured.internal.ValidatableResponseOptionsImpl.statusCode(ValidatableResponseOptionsImpl.java:117)
at assertions.AssertStatusCode.assertStatusCodeIsOk(AssertStatusCode.java:11)
at business.TestBO.callNonExistentFunction_aroundBody0(TestBO.java:29)
... 18 more
]]>
            </full-stacktrace>
          </exception> <!-- exeptions.BaseException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- nonExistFunctionFailTest -->
      </class> <!-- simpleTests.FallTest -->
    </test> <!-- All tests -->
  </suite> <!-- Test -->
</testng-results>
